### ISSUE TITLE
[BUG] Don't assume a row will always be in one line

### ISSUE THREAD

**Issue by 2upmedia** [jwage/easy-csv#35]
Allow cells with carriage returns.

**Comment by moshie** [comment]
Any news on this?

I can't figure out any real way of catching the error produced on line 71 of the Reader.php since the get row method is called in a while?

**Comment by jwage** [comment]
@moshie I haven't seen a PR come in for this yet unfortunately.

**Comment by moshie** [comment]
I was just looking at the code.. 

Not sure what your thoughts are on this but I quickly drafted this up for line 76: https://github.com/jwage/easy-csv/blob/master/lib/EasyCSV/Reader.php#L76

```php
if ($this->headers && is_array($this->headers)) {
	if (count($this->headers) !== count($row)) {
		// Handle incorrect row size
                // Perhaps ignore and move onto the next line?
                return $this->getRow();
	}
	
	return array_combine($this->headers, $row);
}

return $row;
```

**Comment by jwage** [comment]
Hi @moshie I would accept a pull request that contains the change and a test that covers the functionality.

**Comment by brutto** [comment]
Hi all! Have the same problem (csv with multiline rows) and find this MR. How soon it will be tagged in new version?

**Comment by jwage** [comment]
I can tag a new version in the next week or so, maybe tonight.

**Comment by jwage** [comment]
Tagged 0.0.6 with this fix https://github.com/jwage/easy-csv/releases/tag/0.0.6
